# Generated by Django 4.0.5 on 2022-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for_event', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
