# Generated by Django 4.0.5 on 2022-09-12 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for_event', models.DateField(default=datetime.date(2022, 9, 12))),
                ('time_for_event', models.TimeField(null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=250, null=True)),
                ('details', models.TextField(null=True)),
                ('title', models.CharField(max_length=250)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
