# Generated by Django 4.0.5 on 2022-09-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_for_event',
            field=models.DateTimeField(null=True),
        ),
    ]
