# Generated by Django 4.0.5 on 2022-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_task_date_for_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_for_event',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_for_event',
            field=models.DateField(null=True),
        ),
    ]
