# Generated by Django 4.0.5 on 2022-09-13 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_task_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='date_for_event',
            field=models.DateField(default=datetime.date(2022, 9, 13)),
        ),
    ]
