# Generated by Django 4.0.5 on 2022-09-12 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_task_address_task_details_task_email_task_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_for_event',
            field=models.DateField(default=datetime.date(2022, 9, 12), null=True),
        ),
    ]
