# Generated by Django 4.0.5 on 2022-09-12 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_alter_task_date_for_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_for_event',
            field=models.DateField(default=datetime.date(2022, 9, 12)),
        ),
    ]
