name: Hello Bot

on:
    pull_request:
        branches:
            - main

    push:

jobs:
    say-hello:
        # os
        runs-on: ubuntu-latest
        # steps
        steps:
            - name: Print a message
              run: echo "Hello From Hello-Bot"

