name: Test my Code

on:
    pull_request:
        branches:
            - main
    
    push:

jobs:
    run_tests:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                    python-version: '3.13'

            - name: Install Pytest
              run: pip install --no-cache-dir pytest

            - name: Run the test suite
              run: pytest
            

