name: Testing with Dockerfile

on:
    pull_request:
        branches:
            - main
    push:

jobs:
    Run_the_Test_Suite:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Build Test Image
              run: docker build -f ./dockerfiles/Dockerfile.test -t test-task-manager .

            - name: Run the Test Suite
              run: docker run --rm test-task-manager
